### ISSUE TITLE
canvas在页面滚动时定位不对

### ISSUE THREAD

**Issue by rootzm** [buuing/creep-cube#11]
![image](https://user-images.githubusercontent.com/56421757/123071472-4298aa80-d447-11eb-865e-cbda992068bd.png)

**Comment by buuing** [comment]
你这是微信开发者工具吗? 什么版本? 用的哪个基准库? 上传体验版试试? 多留点有用的信息, 我总不能靠猜吧

**Comment by rootzm** [comment]
微信工具 RC 1.05.2104251 2.14.1 调试库， 体验版正常的，昨天没上传测试

**Comment by buuing** [comment]
哦哦, 以体验版为准, 开发者工具一堆bug
